### ISSUE TITLE
Can u have a look to my issue???

### ISSUE THREAD

**Issue by TongKang1** [mcdoeswhat/TwilightPortal#1]
the server i used is spigot-1.12.2, but after i add TwilightPortal in plugin. It cannot work.

[09:45:42 ERROR]: Could not load 'plugins/TwilightPortal.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.util.zip.ZipException: zip END header not found
        at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1535) ~[?:?]
        at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1436) ~[?:?]
        at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1443) ~[?:?]
        at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1274) ~[?:?]
        at java.util.zip.ZipFile$Source.get(ZipFile.java:1237) ~[?:?]
        at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727) ~[?:?]
        at java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:247) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:177) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:348) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:319) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:285) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        ... 5 more

So, what should i do to solve this problem??? Please help me.

**Comment by mcdoeswhat** [comment]
try restart again

**Comment by TongKang1** [comment]
> try restart again

I try it. And found it run in win10 platform server perfectly(with Oracle JDK). But it failed on Ubuntu server (with open JDK). Could it caused by Java version???

**Comment by TongKang1** [comment]
> try restart again

i found the problem. Because i download it with wget, and i download the wrong file, after i remove the original one, and retry, it work. Thank you the mod that you provide. It work very well.
